<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IS_WSL)' == 'true'">
    <IntermediateOutputPath>/tmp/Landform/RayTraceTest/obj/</IntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Geometry/Geometry.csproj" />
    <ProjectReference Include="../Imaging/Imaging.csproj" />
    <ProjectReference Include="../RayTrace/RayTrace.csproj" />
    <ProjectReference Include="../TestExtensions/TestExtensions.csproj" />
    <ProjectReference Include="../Xna/Xna.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../test-data/raptor.obj">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/raptor.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/raptor.mtl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
