<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Geometry/Geometry.csproj" />
    <ProjectReference Include="../Imaging/Imaging.csproj" />
    <ProjectReference Include="../MathExtensions/MathExtensions.csproj" />
    <ProjectReference Include="../TestExtensions/TestExtensions.csproj" />
    <ProjectReference Include="../Util/Util.csproj" />
    <ProjectReference Include="../Xna/Xna.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../test-data/NLB_451649560RNGLF0311330NCAM12813M1.IMG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/utah_teapot_binary.stl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
     <Content Include="../../test-data/utah_teapot_ascii.stl">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/blender_ascii_nct.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/cloudcompare_ascii_nc_.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/cloudcompare_bin_nc_.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_ascii____.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_ascii___t.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_ascii__c_.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include=" ../../test-data/meshlab_ascii__ct.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_ascii_n__.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_ascii_n_t.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_ascii_nc_.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_ascii_nct.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_bin____.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_bin___t.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_bin__c_.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_bin__ct.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_bin_n__.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_bin_n_t.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_bin_nc_.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/meshlab_bin_nct.ply">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

