branch-defaults:
  default:
    environment: landformweb
    group_suffix: null
  master:
    environment: null
    group_suffix: null
deploy:
  artifact: ./landformweb.zip
environment-defaults:
  onsight:
    branch: null
    repository: null
  onsight-staging:
    branch: null
    repository: null
global:
  application_name: landform
  default_region: us-west-1
  profile: eb-cli
  sc: null
