using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.DocumentModel;
using Amazon.DynamoDBv2.Model;
using Amazon.DynamoDBv2;
using Amazon;
using OPS.Cloud;
using OPS.Pipeline;
using OPS.Pipeline.AlignmentServer;
using Microsoft.Xna.Framework;
using log4net;

namespace PipelineTest
{
    //This isn't intended to run with all the tests, since it requires a database connection
    //and won't clean up after itself. (it tries, but won't if it fails)
    [TestClass]
    public class DatabaseTest
    {
        private const string project = "TEST";
        private const string project2 = "TEST2";
        private const string frame = "root-test";
        private const string frame2 = "ant-perspective";

        private Project p;
        private Project p2;
        private Frame f1;
        private Frame f2;
        private Frame f1p2;
        private Frame f2p2;
        private Frame fgenerated;

        //[TestMethod] //Don't automatically run this test, since it interacts with Dynamodb irl
        public void FrameTransformTest()
        {
            CloudPipelineConfig.Instance.Venue = "test";
            PipelineCore pipeline =
                new CloudPipeline(new PipelineCoreOptions { Quiet = false, Debug = false }, enableS3: false);

            //set up project, some frames 
            p = Project.Create(pipeline, project, "url", "url2");
            p2 = Project.Create(pipeline, project2, "url", "url2");
            f1 = Frame.Create(pipeline, project, frame); 
            f2 = Frame.Create(pipeline, project, frame2);
            f1p2 = Frame.Create(pipeline, project2, frame); //frame in other project
            f2p2 = Frame.Create(pipeline, project2, frame2);
            fgenerated = Frame.Create(pipeline, project2); //autogenerated name 
            Thread.Sleep(5); //wait a bit for database consistency 
            Assert.AreEqual(5, pipeline.ScanDatabase<Frame>("ProjectName", project).Count()
                            + pipeline.ScanDatabase<Frame>("ProjectName", project2).Count()); //check for both project names

            //delete frame with generated name 
            pipeline.DeleteDatabaseItem(fgenerated);
            /*
            //Multiple ids for a project in same transform lookup
            FrameTransform ft1 = FrameTransform.Create(pipeline, f1, f2, Vector3.Zero, Quaternion.Identity, TransformSource.Prior, .01);
            Assert.AreEqual(1, FrameTransform.Find(pipeline, f1, f2).Count());
            FrameTransform ft2 = FrameTransform.Create(pipeline, f1, f2, Vector3.Down, Quaternion.Identity, TransformSource.Prior, .01);
            Assert.AreEqual(2, FrameTransform.Find(pipeline, f1, f2).Count());
            //Create frame in other project and make sure it shows up correctly, even if names are the same
            FrameTransform ft1p2 = FrameTransform.Create(pipeline, f1p2, f2p2, Vector3.Zero, Quaternion.Identity, TransformSource.Prior, .01);
            Assert.AreEqual(1, FrameTransform.Find(pipeline, f1p2, f2p2).Count());
            */

            //Multiple projects in same transform lookup

            //Simultaneous creation and insertion for same transform & project 

            cleanup(pipeline);

        }

        private void cleanup(PipelineCore pipeline)
        {
            pipeline.DeleteDatabaseItem(p);
            pipeline.DeleteDatabaseItem(p2);
            pipeline.DeleteDatabaseItem(f1);
            pipeline.DeleteDatabaseItem(f2);
            pipeline.DeleteDatabaseItem(f1p2);
            pipeline.DeleteDatabaseItem(f2p2);
            pipeline.DeleteDatabaseItem(fgenerated);
            //todo clean up all tables based on project name 
        }

    }
}
