using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using Amazon.DynamoDBv2.DataModel;
using Amazon.DynamoDBv2.Model;
using Amazon.DynamoDBv2;
using Amazon;
using OPS.Cloud;

using Microsoft.Xna.Framework;

namespace CloudTest
{
    //This isn't intended to run with all the tests, since it requires a database connection
    //and won't clean up after itself. (it tries, but won't if it fails)
    [TestClass]
    public class DatabaseTest
    {
        private const string project = "TEST";
        private const string project2 = "TEST2";
        private const string frame = "root-test";
        private const string frame2 = "ant-perspective";

        //[TestMethod] //Don't automatically run this test, since it interacts with Dynamodb irl
        public void FrameTransformTest()
        {
            DynamoDBContext context = new DynamoDBContext(new AmazonDynamoDBClient(Amazon.RegionEndpoint.USWest1),
                new DynamoDBContextConfig { TableNamePrefix = "dev0-"});

            //set up project, some frames 
            Project p = Project.Create(context, project, "url", "url2");
            Project p2 = Project.Create(context, project2, "url", "url2");
            Frame f1 = Frame.Create(context, p, frame); 
            Frame f2 = Frame.Create(context, p, frame2);
            Frame f1p2 = Frame.Create(context, p2, frame); //frame in other project
            Frame f2p2 = Frame.Create(context, p2, frame2);
            Frame fgenerated = Frame.Create(context, p2); //autogenerated name 
            Thread.Sleep(5); //wait a bit for database consistency 
            Assert.AreEqual(5, context.Scan<Frame>(new ScanCondition("ProjectName", 
                Amazon.DynamoDBv2.DocumentModel.ScanOperator.Equal, project)).Count()
                + context.Scan<Frame>(new ScanCondition("ProjectName",
                Amazon.DynamoDBv2.DocumentModel.ScanOperator.Equal, project2)).Count()); //check for both project names

            //delete frame with generated name 
            context.Delete<Frame>(fgenerated);

            //Multiple ids for a project in same transform lookup
            FrameTransform ft1 = FrameTransform.Create(context, f1, f2, Vector3.Zero, Quaternion.Identity, TransformSource.Prior, .01);
            Assert.AreEqual(1, FrameTransform.Find(context, f1, f2).Count());
            FrameTransform ft2 = FrameTransform.Create(context, f1, f2, Vector3.Down, Quaternion.Identity, TransformSource.Prior, .01);
            Assert.AreEqual(2, FrameTransform.Find(context, f1, f2).Count());
            //Create frame in other project and make sure it shows up correctly, even if names are the same
            FrameTransform ft1p2 = FrameTransform.Create(context, f1p2, f2p2, Vector3.Zero, Quaternion.Identity, TransformSource.Prior, .01);
            Assert.AreEqual(1, FrameTransform.Find(context, f1p2, f2p2).Count());


            //Multiple projects in same transform lookup

            //Simultaneous creation and insertion for same transform & project 

            cleanup(context);

        }

        private void cleanup(DynamoDBContext context)
        {
            context.Delete<Project>(project);
            context.Delete<Project>(project2);
            context.Delete<Frame>(frame, project);
            context.Delete<Frame>(frame2, project);
            context.Delete<Frame>(frame, project2);
            context.Delete<Frame>(frame2, project2);
            context.Delete<Frame>(frame, project);
//todo clean up all tables based on project name 
        }

    }
}
