<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Imaging/Imaging.csproj" />
    <ProjectReference Include="../MathExtensions/MathExtensions.csproj" />
    <ProjectReference Include="../TestExtensions/TestExtensions.csproj" />
    <ProjectReference Include="../Xna/Xna.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../test-data/testPattern.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/FLB_509619692RAS_T0530000FHAZ00323M1.IMG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/ML0_451292526RCX_S0311094MCAM02555M1.IMG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/NLB_451649560RNGLF0311330NCAM12813M1.IMG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/NLB_451025090ARMLF0311052NCAM00493M1.IMG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="../../test-data/0608ML0025660260301542E01_DRCX.IMG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
