<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyTitle>CloudMessages</AssemblyTitle>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssemblyName>CloudMessagesCore</AssemblyName>
    <PackageId>CloudMessagesCore</PackageId>
    <RuntimeFrameworkVersion>2.0.0</RuntimeFrameworkVersion>
    <NetStandardImplicitPackageVersion>2.0.0</NetStandardImplicitPackageVersion>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\*Message.cs;..\CloudException.cs;..\Properties\AssemblyInfo.cs" Exclude="bin\**;obj\**;**\*.xproj;packages\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.SQS" Version="3.3.3.2" />
    <PackageReference Include="Newtonsoft.Json" Version="11.0.1" />
  </ItemGroup>

</Project>
